version: '3.8'

services:
  app:
    build:
      context: .
    container_name: be_kelolacermat
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql_kc
      - DB_PORT=3306
      - DB_DATABASE=db_kelolacermat
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis_kc
      - REDIS_PORT=6379
      - CACHE_STORE=redis
      - CACHE_DRIVER=redis
      - REDIS_PASSWORD=S3cretJohnDev1!
    depends_on:
      - mysql_kc
      - redis_kc
    networks:
      - laravel_network

  mysql_kc:
    image: mysql:8.0
    container_name: mysql_kc
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_kelolacermat
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  redis_kc:
    image: redis
    container_name: redis_kc
    command: ["redis-server", "--requirepass", "S3cretJohnDev1!"]
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel_network

  phpmyadmin_kc:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_kc
    restart: unless-stopped
    environment:
      PMA_HOST: mysql_kc
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql_kc
    networks:
      - laravel_network

volumes:
  mysql_data:
  redis_data:

networks:
  laravel_network:
    driver: bridge