version: '3.8'

services:
  app:
    build:
      context: .
    container_name: franken_laravel
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./vendor:/app/vendor
      - ./storage:/app/storage
      - ./.env:/app/.env
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel_franken
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_STORE=redis
      - CACHE_DRIVER=redis
      - REDIS_PASSWORD=S3cretJohnDev1!
    depends_on:
      - mysql
      - redis
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_franken
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  redis:
    image: redis
    container_name: redis
    command: ["redis-server", "--requirepass", "S3cretJohnDev1!"]
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - laravel_network

volumes:
  mysql_data:
  redis_data:

networks:
  laravel_network:
    driver: bridge